# TAS50: THIS COOKBOOK DELIBERATELY DOES NOT USE THE STANDARD TRAVIS.YML FILE
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

branches:
  only:
    - master

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

matrix:
  include:
    - rvm: 2.4.1
      before_script:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      install: echo "skip bundle install"
      script:
        - /opt/chefdk/embedded/bin/chef --version
        - /opt/chefdk/embedded/bin/cookstyle --version
        - /opt/chefdk/embedded/bin/foodcritic --version
        - /opt/chefdk/bin/chef exec delivery local all
    - rvm: 2.4.1
      services: docker
      sudo: required
      before_script:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
        - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      # 11.10.4 is the earliest we can test due to test-kitchen / chef-zero not supporting earlier
      # (cookbook likely supports earlier versions)
      env:
        - OMNIBUS_CHEF_VERSION=11.18.12
        - KITCHEN_YAML=.kitchen.dokken.yml
      script:
        - bundle exec kitchen test default-ubuntu-1604
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.ancient
      script:
        - bundle exec rspec
